" Vim syntax file
" Language: Wet (stack-based scripting language)
" Maintainer: Generated by Claude Code
" Latest Revision: 2025-11-07

if exists("b:current_syntax")
  finish
endif

" Comments
syn match wetComment "\v^#.*$"
syn match wetComment "\v^//.*$"

" Keywords - Control Flow
syn keyword wetKeyword if else end while until do macro proc until unless

" Stack Operations
syn keyword wetStackOp dup drop swap over 2dup 2swap nop

" Memory Operations
syn keyword wetMemory store load

" Output Operations
syn keyword wetOutput puts

" Type Conversion
syn keyword wetType int string

" Tool Operations
syn keyword wetTool download readfile move copy exist touch mkdir rm unzip lsf getf lsd getd concat tostring token absolute relative

" Boolean Literals
syn keyword wetBoolean true false

" Operators - Arithmetic
syn match wetOperator "\v\+"
syn match wetOperator "\v-"
syn match wetOperator "\v\*"
syn match wetOperator "\v/"
syn match wetOperator "\v\%"
syn match wetOperator "\v\+\+"
syn match wetOperator "\v\-\-"

" Operators - Comparison
syn match wetOperator "\v\="
syn match wetOperator "\v\!\="
syn match wetOperator "\v\<"
syn match wetOperator "\v\>"
syn match wetOperator "\v\<\="
syn match wetOperator "\v\>\="

" Operators - Bitwise
syn match wetOperator "\v\&"
syn match wetOperator "\v\|"
syn match wetOperator "\v\^"
syn match wetOperator "\v\~"

" Operators - Logical
syn match wetOperator "\v\!"
syn match wetOperator "\v\&\&"
syn match wetOperator "\v\|\|"

" Special Print Operator
syn match wetOperator "\v\."

" Numbers (integers, including negative)
syn match wetNumber "\v<-?\d+>"

" Strings (double-quoted with escape sequences)
syn region wetString start='"' end='"' skip='\\"' contains=wetStringEscape
syn match wetStringEscape contained "\\[ntr\\"]"

" Resource Paths
syn match wetPath "\v^/([^ \\]|\\.)*"
syn match wetPath "\v^\./([^ \\]|\\.)*"
syn match wetPath "\v:([^ \\]|\\.)+"

" Macro Names (after 'macro' keyword)
syn match wetMacroName "\v((macro|proc)\s+)@<=\w+"

" Link to standard highlighting groups
hi def link wetComment Comment
hi def link wetKeyword Keyword
hi def link wetStackOp Function
hi def link wetMemory StorageClass
hi def link wetOutput Statement
hi def link wetType Type
hi def link wetTool Identifier
hi def link wetBoolean Boolean
hi def link wetOperator Operator
hi def link wetNumber Number
hi def link wetString String
hi def link wetStringEscape SpecialChar
hi def link wetPath Constant
hi def link wetMacroName Identifier

let b:current_syntax = "wet"
