name: Test Wet

on:
  push:
    branches:
      - master
      - dev
      - tests
    paths:
      - '**'
      - '.github/workflows/**'

jobs:
  test-linux:
    name: Test Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.3'

      - name: Validate Go
        run: go version

      - name: Build - Generate
        run: go generate ./...
      - name: Build - Tidy
        run: go mod tidy
      - name: Build - Vet
        run: go vet ./...
      - name: Build CLI
        run: go build -o wet cmd/cli/main.go
      - name: Build Test
        run: go build -o test cmd/test/main.go

      - name: Test Wet
        run: |
          chmod +x ./test
          ./test

  test-windows:
    name: Test Windows
    runs-on: windows-latest
    steps:
      - name: Setup Git
        run: git config --global core.autocrlf false

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.3'

      - name: Validate Go
        run: go version

      - name: Build - Generate
        shell: cmd
        run: go generate ./...
      - name: Build - Tidy
        shell: cmd
        run: go mod tidy
      - name: Build - Vet
        shell: cmd
        run: go vet ./...
      - name: Build CLI
        shell: cmd
        run: go build -o wet.exe cmd/cli/main.go
      - name: Build Test
        shell: cmd
        run: go build -o test.exe cmd/test/main.go

      - name: Test Wet
        shell: cmd
        run: |
          test.exe
